// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelApp.Repository.Concrete;

namespace TravelApp.Migrations
{
    [DbContext(typeof(TravelContext))]
    [Migration("20210422192650_AddOtelTable")]
    partial class AddOtelTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TravelApp.Models.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BlogBody");

                    b.Property<string>("BlogDescription");

                    b.Property<string>("BlogImage");

                    b.Property<string>("BlogTittle");

                    b.Property<bool>("isShared");

                    b.Property<bool>("isSlider");

                    b.HasKey("BlogId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("TravelApp.Models.Otel", b =>
                {
                    b.Property<int>("OtelId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SehirId");

                    b.Property<string>("otelAciklama");

                    b.Property<string>("otelAd");

                    b.Property<string>("otelAdres");

                    b.Property<string>("otelImage");

                    b.Property<double>("otelPuan");

                    b.Property<string>("otelTel");

                    b.HasKey("OtelId");

                    b.HasIndex("SehirId");

                    b.ToTable("Otels");
                });

            modelBuilder.Entity("TravelApp.Models.Sehir", b =>
                {
                    b.Property<int>("SehirId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Plaka");

                    b.Property<string>("sehirAd");

                    b.HasKey("SehirId");

                    b.ToTable("Sehirs");
                });

            modelBuilder.Entity("TravelApp.Models.Otel", b =>
                {
                    b.HasOne("TravelApp.Models.Sehir", "Sehir")
                        .WithMany("Otels")
                        .HasForeignKey("SehirId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
